### PR TITLE
disable session resolution on Act testbed

### PR DESCRIPTION
**Pull request by greenlaw110**
Act by default try to resolve session cookie from request. This updates disable this behavior and should improve Act's benchmark result

### CODE REVIEW

**Comment by greenlaw110** [comment]
@stevehu thanks for accept the pull request. Do you mind run benchmark on Act again? I believe there should be some improvement with this pull request.

Cheers and Happy Chinese New Year!

**Comment by stevehu** [comment]
I will do that tonight. I have to run the test from the same desktop at home. Happy Chinese New Year!

**Comment by stevehu** [comment]
Got this error with the pull request.

```
21:11:44.682 [cli-thread-4] ERROR a.Act - Broken pipe
21:11:44.682 [cli-thread-3] ERROR a.Act - Broken pipe
21:11:44.683 [cli-thread-5] ERROR a.Act - Broken pipe
21:11:44.684 [cli-thread-4] ERROR a.Act - Broken pipe
21:11:44.685 [cli-thread-5] ERROR a.Act - Broken pipe
21:11:44.685 [cli-thread-3] ERROR a.Act - Broken pipe
21:11:44.685 [cli-thread-4] ERROR a.Act - Broken pipe
21:11:44.686 [cli-thread-5] ERROR a.Act - Broken pipe
21:11:44.686 [cli-thread-3] ERROR a.Act - Broken pipe
21:11:44.687 [cli-thread-4] ERROR a.Act - Broken pipe
21:11:44.687 [cli-thread-5] ERROR a.Act - Broken pipe
21:11:44.688 [cli-thread-3] ERROR a.Act - Broken pipe
21:11:44.688 [cli-thread-4] ERROR a.Act - Broken pipe
21:11:44.689 [cli-thread-5] ERROR a.Act - Broken pipe
21:11:44.690 [cli-thread-3] ERROR a.Act - Broken pipe
21:11:44.690 [cli-thread-4] ERROR a.Act - Broken pipe
```

**Comment by greenlaw110** [comment]
That's weird. My test looks okay:
image


Can you please run the following?

```
# use -U to force update snapshot
mvn -U clean package
cd target/dist
unzip *.zip
./start
```

**Comment by stevehu** [comment]
Still the same error.

**Comment by greenlaw110** [comment]
hmm... doesn't sound good. Is there any chance for us to have a screen share session?

**Comment by greenlaw110** [comment]
my email is `greenlaw110@gmail.com`. please drop me an email if possible.

**Comment by greenlaw110** [comment]
@stevehu I've tuned actframework by removing an unnecessary synchronization and the result is incredible:

image

**Comment by stevehu** [comment]
Yes. Send me a pull request please.

**Comment by greenlaw110** [comment]
No need for pull request. There is no code change in the testbed. Just type

```
mvn -U clean package
cd target/dist
unzip *.zip
./start
```

to run the test bed, it will automatically pull the new Act snapshot

**Comment by stevehu** [comment]
followed the above instruction and got the following errors.

steve@joy:~/networknt/light-java-example/performance/actframework/target/dist$ ./start
Picked up JAVA_TOOL_OPTIONS: -Dconfig.dir=/home/steve/config
 _   _        _  _         __        __              _      _ 
| | | |  ___ | || |  ___   \ \      / /  ___   _ __ | |  __| |
| |_| | / _ \| || | / _ \   \ \ /\ / /  / _ \ | '__|| | / _` |
|  _  ||  __/| || || (_) |   \ V  V /  | (_) || |   | || (_| |
|_| |_| \___||_||_| \___/     \_/\_/    \___/ |_|   |_| \__,_|
                                                              
                          powered by ActFramework v0.3.1-a4414

 version: 0.0.1-SNAPSHOT
base dir: /home/steve/networknt/light-java-example/performance/actframework/target/dist
     pid: 6644
 profile: prod
    mode: PROD
   group: 

     zen: Flat is better than nested.

13:23:01.064 [main] INFO  o.h.v.i.u.Version - HV000001: Hibernate Validator 5.1.3.Final
13:23:01.108 [main] INFO  a.Act - loading application(s) ...
13:23:01.110 [main] INFO  a.Act - App starting ....
Exception in thread "main" org.osgl.exception.UnexpectedException: Unknown error captured starting the application
	at org.osgl.util.E.unexpected(E.java:104)
	at act.boot.app.RunApp.start(RunApp.java:70)
	at act.boot.app.RunApp.start(RunApp.java:42)
	at demo.Example.main(Example.java:29)
Caused by: java.lang.NoSuchMethodError: org.osgl.mvc.MvcConfig.messageTranslater(Lorg/osgl/Osgl$Function;)V
	at act.conf.AppConfig.<clinit>(AppConfig.java:57)
	at act.conf.AppConfLoader.create(AppConfLoader.java:8)
	at act.conf.AppConfLoader.create(AppConfLoader.java:5)
	at act.conf.ConfLoader.load(ConfLoader.java:48)
	at act.app.App.loadConfig(App.java:730)
	at act.app.App.refresh(App.java:402)
	at act.app.AppManager.load(AppManager.java:63)
	at act.app.AppManager$_F$1.visit(AppManager.java:135)
	at act.app.AppManager$_F$1.visit(AppManager.java:131)
	at org.osgl.Osgl$Visitor.apply(Osgl.java:2226)
	at org.osgl.Osgl$Visitor.apply(Osgl.java:2216)
	at act.app.AppScanner.scan(AppScanner.java:74)
	at act.app.AppScanner.scan(AppScanner.java:54)
	at act.app.AppManager.loadSingleApp(AppManager.java:41)
	at act.Act.start(Act.java:286)
	at act.Act.startApp(Act.java:257)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at act.boot.app.RunApp.start(RunApp.java:64)
	... 2 more

**Comment by stevehu** [comment]
```
steve@joy:~/networknt/light-java-example/performance/actframework/target/dist$ ./start
Picked up JAVA_TOOL_OPTIONS: -Dconfig.dir=/home/steve/config
 _   _        _  _         __        __              _      _ 
| | | |  ___ | || |  ___   \ \      / /  ___   _ __ | |  __| |
| |_| | / _ \| || | / _ \   \ \ /\ / /  / _ \ | '__|| | / _` |
|  _  ||  __/| || || (_) |   \ V  V /  | (_) || |   | || (_| |
|_| |_| \___||_||_| \___/     \_/\_/    \___/ |_|   |_| \__,_|
                                                              
                          powered by ActFramework v0.3.1-a4414

 version: 0.0.1-SNAPSHOT
base dir: /home/steve/networknt/light-java-example/performance/actframework/target/dist
     pid: 6644
 profile: prod
    mode: PROD
   group: 

     zen: Flat is better than nested.

13:23:01.064 [main] INFO  o.h.v.i.u.Version - HV000001: Hibernate Validator 5.1.3.Final
13:23:01.108 [main] INFO  a.Act - loading application(s) ...
13:23:01.110 [main] INFO  a.Act - App starting ....
Exception in thread "main" org.osgl.exception.UnexpectedException: Unknown error captured starting the application
	at org.osgl.util.E.unexpected(E.java:104)
	at act.boot.app.RunApp.start(RunApp.java:70)
	at act.boot.app.RunApp.start(RunApp.java:42)
	at demo.Example.main(Example.java:29)
Caused by: java.lang.NoSuchMethodError: org.osgl.mvc.MvcConfig.messageTranslater(Lorg/osgl/Osgl$Function;)V
	at act.conf.AppConfig.<clinit>(AppConfig.java:57)
	at act.conf.AppConfLoader.create(AppConfLoader.java:8)
	at act.conf.AppConfLoader.create(AppConfLoader.java:5)
	at act.conf.ConfLoader.load(ConfLoader.java:48)
	at act.app.App.loadConfig(App.java:730)
	at act.app.App.refresh(App.java:402)
	at act.app.AppManager.load(AppManager.java:63)
	at act.app.AppManager$_F$1.visit(AppManager.java:135)
	at act.app.AppManager$_F$1.visit(AppManager.java:131)
	at org.osgl.Osgl$Visitor.apply(Osgl.java:2226)
	at org.osgl.Osgl$Visitor.apply(Osgl.java:2216)
	at act.app.AppScanner.scan(AppScanner.java:74)
	at act.app.AppScanner.scan(AppScanner.java:54)
	at act.app.AppManager.loadSingleApp(AppManager.java:41)
	at act.Act.start(Act.java:286)
	at act.Act.startApp(Act.java:257)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at act.boot.app.RunApp.start(RunApp.java:64)
	... 2 more

```

**Comment by greenlaw110** [comment]
Well, something wrong with the dependency. Can you list all jar files inside the `/lib` dir?

**Comment by greenlaw110** [comment]
I've updated snapshot versions this morning. You probably can check it again.

**Comment by stevehu** [comment]
The server can be started this time but got the following error again.

```
17:59:12.164 [cli-thread-4] ERROR a.Act - Broken pipe
17:59:12.164 [cli-thread-5] ERROR a.Act - Broken pipe
17:59:12.164 [cli-thread-3] ERROR a.Act - Broken pipe
17:59:12.169 [cli-thread-4] ERROR a.Act - Broken pipe
17:59:12.172 [cli-thread-3] ERROR a.Act - Broken pipe
17:59:12.180 [cli-thread-5] ERROR a.Act - Broken pipe
17:59:12.180 [cli-thread-4] ERROR a.Act - Broken pipe
17:59:12.181 [cli-thread-4] ERROR a.Act - Broken pipe
17:59:12.186 [cli-thread-3] ERROR a.Act - Broken pipe
17:59:12.188 [cli-thread-5] ERROR a.Act - Broken pipe
17:59:12.192 [cli-thread-4] ERROR a.Act - Broken pipe
17:59:12.196 [cli-thread-3] ERROR a.Act - Broken pipe
17:59:12.200 [cli-thread-5] ERROR a.Act - Broken pipe
17:59:12.204 [cli-thread-4] ERROR a.Act - Broken pipe
17:59:12.210 [cli-thread-3] ERROR a.Act - Broken pipe
17:59:12.211 [cli-thread-5] ERROR a.Act - Broken pipe
17:59:12.212 [cli-thread-4] ERROR a.Act - Broken pipe
17:59:12.213 [cli-thread-3] ERROR a.Act - Broken pipe
17:59:12.214 [cli-thread-5] ERROR a.Act - Broken pipe
17:59:12.214 [cli-thread-4] ERROR a.Act - Broken pipe

```

**Comment by greenlaw110** [comment]
looks like the request is sent to CLI port (a port for telnet access), by default it is 5461, and the http port is 5460, which should be tested against.

**Pull request merged**
