### PR TITLE
Bootique + Jetty/Jersey performance test.

### PR DESCRIPTION
**Pull request by IRus**
Hi! I contribute "Hello World!" with Bootique.

### CODE REVIEW

**Comment by IRus** [comment]
So this is results on my machine:
```
# bootique-jetty

Running 30s test @ http://localhost:8080
  4 threads and 128 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   106.02ms   88.19ms 793.04ms   76.92%
    Req/Sec     4.19k     1.34k    9.88k    72.38%
  Latency Distribution
     50%   81.36ms
     75%  146.31ms
     90%  227.42ms
     99%  402.40ms
  500070 requests in 30.06s, 85.84MB read
Requests/sec:  16633.46
Transfer/sec:      2.86MB

# light-java:

Running 30s test @ http://localhost:8080
  4 threads and 128 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     7.21ms   24.06ms 377.06ms   97.30%
    Req/Sec   114.28k    34.93k  245.28k    77.44%
  Latency Distribution
     50%    2.78ms
     75%    5.56ms
     90%   10.66ms
     99%  113.04ms
  13542736 requests in 30.08s, 1.34GB read
Requests/sec: 450150.50
Transfer/sec:     45.51MB
```

**Comment by stevehu** [comment]
@IRus Thanks for your contribution. I will run the test tonight on my home desktop. Is your a laptop or desktop?

**Comment by IRus** [comment]
Laptop with working applications, so this results not too precise. 
Intel® Core™ i5-3317U CPU @ 1.70GHz × 4, 9.7 GiB RAM

**Comment by stevehu** [comment]
That is very reasonable result. I guess it will be between 40K to 50K on my desktop.

**Comment by IRus** [comment]
Not too bad actually. Because basically it's test of jetty+jersey stack.

**Comment by stevehu** [comment]
I tried to build on my desktop and got the following error. I am not familiar with Gradle and it might be my installation issue. Should gradle be downloaded automatically? Thanks.
steve@joy:~/networknt/light-java-example/performance/bootique-jetty$ ./gradlew shadowJar
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain

**Comment by IRus** [comment]
My bad, i forgot to include wrapper actually. One moment.

**Comment by IRus** [comment]
https://github.com/networknt/light-java-example/pull/7

**Comment by IRus** [comment]
It's just few KB and it's common practice to include it to repository.

**Pull request merged**
